Application State : Good (0), Error (non-Zero)
antaris-inc/SatOS-Payload-SDK pull request #22
Opened 2023-10-03 12:24 UTC by rahulbhivare

2023-10-04 07:15 UTC, deepaktawri requested changes
Not sure why this change is required. Current code is correct. Its boolean question if app is active or not. May be 1 can be replaced by TRUE.

2023-10-04 08:07 UTC, omkar-sp commented
> Not sure why this change is required. Current code is correct. Its boolean question if app is active or not. May be 1 can be replaced by TRUE.

There can be more values for the state than ACTIVE. All non-zero values will be considered as error states. Hence ACTIVE state is set to 0.

2023-10-04 08:20 UTC, omkar-sp approved these changes

2023-10-04 08:26 UTC, rahulbhivare commented
> Not sure why this change is required. Current code is correct. Its boolean question if app is active or not. May be 1 can be replaced by TRUE.

The reason is :- Python application is sending '0' as success and hence c++ should also send '0' for success.

2023-10-06 07:09 UTC, deepaktawri approved these changes

2023-10-10 07:13 UTC, merged